### ISSUE TITLE
Linkin error: `member '/' not a mach-o file in .../libVideoKit.a` on iOS build

### ISSUE THREAD

**Issue by mentarus** [natml-hub/MoveNet#8]
Tried building the example as per the repository with only changes to the certificate for the project and the UnityFramework in xcode but keep getting the following error:
`archive member '/' not a mach-o file in '.../VibeMoveNetiOS/Libraries/ai.natml.videokit/Plugins/Web/libVideoKit.a'`

**Comment by olokobayusuf** [comment]
Hey @mentarus sorry for the delayed response on this. I recommend switching to using [MoveNet Multipose](https://github.com/natmlx/movenet-multipose-unity).
